version: '3.8'
services:
  db:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: POSTGRESS
      POSTGRES_PASSWORD: DEVDB123
      POSTGRES_DB: AUTH_AUTHZ
    networks:
      - AUTH_AUTHZ
networks:
  AUTH_AUTHZ:
